// used to put images on the gallery grid in a specific order
export const Media = [
    {type: 'image', url: require('./images/Fish_Lures1.jpg')},
    {type: 'image', url: require('./images/Fish_Lures2.jpg')},
    {type: 'image', url: require('./images/Fish_Lures3.jpg')},
    {type: 'image', url: require('./images/Fish_Lures4.jpg')},
    {type: 'image', url: require('./images/Fish_Lures5.jpg')},
    {type: 'image', url: require('./images/Fish_Lures6.jpg')},
    {type: 'image', url: require('./images/Fish_Lures7.jpg')},
    {type: 'image', url: require('./images/Fish_Lures8.jpg')},
    {type: 'image', url: require('./images/Fish_Lures9.jpg')},
    {type: 'image', url: require('./images/Fish_Lures10.jpg')},
    {type: 'image', url: require('./images/FishingP1.jpg')},
    {type: 'image', url: require('./images/FishingP2.jpg')},
    {type: 'image', url: require('./images/FishingP3.jpg')},
    {type: 'image', url: require('./images/FishingP4.jpg')},
    {type: 'image', url: require('./images/FishingP5.jpg')},
    {type: 'image', url: require('./images/FishingP6.jpg')},
    {type: 'image', url: require('./images/FishingP7.jpg')},
    {type: 'image', url: require('./images/FishingP8.jpg')},
    {type: 'image', url: require('./images/FishingP9.jpg')},
    {type: 'image', url: require('./images/FishingP10.jpg')},
    {type: 'image', url: require('./images/FishingP11.jpg')},
    {type: 'image', url: require('./images/Rich1.jpg')},
    {type: 'image', url: require('./images/Rich2.jpg')},
    {type: 'image', url: require('./images/RichnMe.jpg')},
    {type: 'image', url: require('./images/RichnMe2.jpg')}
]